### ISSUE TITLE
Troubleshooting SMPT ?

### ISSUE THREAD

**Issue by NicTanghe** [EmberLightVFX/Kitsu-for-Docker#4]
Hello when sending an email invitation.
THe browser ui indicates that the invitation was succesfully sent.
I do not however receive an email on the receiving email adress.

there was also no sent email from the sending adress.

I was wondering where to go look for trouble shooting information.

i did fill in the the email segment in the .env file

**Comment by johhnry** [comment]
Hi @NicTanghe, make sure that you filled the proper env variables here: https://zou.cg-wire.com/configuration/#emails

You can check the logs by using `docker compose logs` if there are any errors.
